---
- vars_files:
     - vars.yml
  hosts: "{{MASTER_SERVER}}"
  remote_user: jenkins
  tasks:
    - name: Removing docker registry container...
      shell: docker rm -f docker.registry
      ignore_errors: yes
  
    - name: Buiding docker registry container...
      shell: docker run --restart=always --name docker.registry -d -p 5000:5000 -v {{REGISTRY_FOLDER}}:/var/lib/registry registry
      

 



    
    



    
    
