---
- vars_files:
     - vars.yml
  hosts: "{{ALL_ELK_SERVERS}}"
  remote_user: jenkins
  tasks:

    - name: Remove Kibana server containers...
      shell: docker rm -f kibana.server
      ignore_errors: yes

    - name: Remove logstash server containers...
      shell: docker rm -f logstash.server
      ignore_errors: yes
      
    - name: Remove Elastic server containers...
      shell: docker rm -f elastic.server
      ignore_errors: yes
            
    - name:  Create elastic server containers...
      shell: docker run --restart=always -d -p9200:9200 -p9300:9300 -v {{ELASTIC_CONF_FOLDER}}:/usr/share/elasticsearch/config -v {{ELASTIC_DATA_FOLDER}}:/usr/share/elasticsearch/data  --name elastic.server elasticsearch
            
    - name:  Create logstash server containers...
      shell: docker run --restart=always -d  -v {{LOGSTASH_CONF_FOLDER}}:/config-dir -p 3456:3456 --name logstash.server logstash -f /config-dir/logstash.conf

    - name:  Create kibana server containers...
      shell: docker run --restart=always -d --name kibana.server -v {{KIBANA_CONF_FOLDER}}:/etc/kibana -p 5601:5601 kibana
      

 



    
    



    
    
