---
- name: Remove relevant
- vars_files:
     - vars.yml
  hosts: "{{all_servers}}"
  remote_user: jenkins
  tasks:
    - name: Stop consul-template service ...
      shell: service consul-template stop    
      ignore_errors: yes 
    - name: Remove Service Registrator containers ...
      shell: docker rm -f service.registrator   
      ignore_errors: yes 
    - name: Remove Consul Server containers ...
      shell: docker rm -f consul.server    
      ignore_errors: yes 


     



    
    
