---
- vars_files:
     - vars.yml
  hosts: "{{ALL_CONSUL_SERVERS}}"
  remote_user: jenkins
  tasks:
    - name: Stop consul-template service ...
      shell: ANSIBLE_CMD=service consul-template stop && echo $ANSIBLE_CMD && $ANSIBLE_CMD    
      ignore_errors: yes 
 
      



    
    



    
    
