---
- vars_files:
     - vars.yml
  hosts: "{{ALL_CONSUL_SERVERS}}"
  remote_user: jenkins
  tasks:
    - name: Remove Redis Server containers ...
      shell: docker rm -f redis.server   
      ignore_errors: yes

- vars_files:
     - vars.yml
  hosts: "{{MASTER_SERVER}}"
  remote_user: jenkins
  tasks:
    - name: 
      shell: docker run -d -p 6379:6379 -v {{CONF_FOLDER}}:/usr/local/etc/redis/redis.conf --name redis.server {{DOCKER_REP_NAME}} redis-server /usr/local/etc/redis/redis.conf
 
      



    
    



    
    
