##  kubectl delete service kube-test-service | kubectl delete deployment kube-test-deployment
##  kubectl create -f kube-test.yml


apiVersion: v1
kind: Service
metadata:
  name: kube-test-service
spec:
  type: NodePort
  ports:
  - port: 3800
    nodePort: 30082
    targetPort: 3800
  selector:
    app: kube-test-ms
 
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kube-test-deployment
spec:
  selector:
    matchLabels:
      app: kube-test-ms
  strategy:
    type: Recreate
  template:
    metadata:
      name: kube-test-pod
      labels:
        app: kube-test-ms
    spec:
      containers:
      - image: 10.39.101.226:5000/cloud.security.service
        name: kube-test-ms
        ports:
        - containerPort: 3800
 
