---
- vars_files:
     - vars.yml
  hosts: "{{MASTER_SERVER}}"
  remote_user: jenkins
  tasks:
    - name: Remove ds master server container...
      shell: docker rm -f ds.master.server
      ignore_errors: yes
      
    - name:  Create ds master server...
      shell: docker run -d -p 10389:10389 --name ds.master.server {{DOCKER_IMG_NAME}}


 



    
    



    
    
