---
- vars_files:
     - vars.yml
  hosts: "{{ALL_NGINX_SERVERS}}"
  remote_user: jenkins
  tasks:
    - name: Remove consul-template services...
      shell: sudo service stop consul-template-service || sudo update-rc.d -f consul-template-service remove
      sudo: yes
      ignore_errors: yes
 
    - name: Remove nginx server containers...
      shell: docker rm -f nginx.server
      ignore_errors: yes
  
    - name: docker run  {{PORTS}}  -v {{CONF_FOLDER}}:/etc/nginx/nginx.conf --name nginx.server  -d {{DOCKER_IMG_NAME}}
      shell: docker run  {{PORTS}}  -v {{CONF_FOLDER}}:/etc/nginx/nginx.conf --name nginx.server  -d {{DOCKER_IMG_NAME}}
  
    - name: sudo cp {{CONF_SERVICE_FILE}} /etc/init.d/consul-template-service
      sudo: yes
      shell: sudo cp {{CONF_SERVICE_FILE}} /etc/init.d/consul-template-service && sudo chmod +x /etc/init.d/consul-template-service
      
    - name: Enable consul-template service...
      sudo: yes
      shell: sudo update-rc.d consul-template-service enable 
      
    - name: Create consul-template service...
      sudo: yes
      shell: sudo update-rc.d consul-template-service defaults 
       
    - name: Start consul-template service...
      sudo: yes
      shell: sudo service consul-template-service start 
      
    

 
   



    
    



    
    
